### ISSUE TITLE
How to build windows executable

### ISSUE THREAD

**Issue by HashEngineering** [coinsurenz/btc-key-gui#1]
I tried to build a windows executable on my system using:
`pyinstaller --onefile bip39_gui.py`

But when it is run, it starts with a blank console and closes down about 5 seconds later.

On the same system `python bip39_gui.py` does run.

I have Python 3.8.1 on Windows 10.

Is there a better build method?

**Comment by HashEngineering** [comment]
After following the documentation which mentions using python 3.6, I found that building the windows binary was successful.

**Comment by coinsurenz** [comment]
Thanks for making me aware- hoping to finally have the time to update this repo in the coming weeks and will look into whether there are some issues with new versions of Python
